# General parameters
organism: h # set h for human, m for mouse
gtf: /path/to/gene_annotation.gtf
genome_fasta: /path/to/dna.primary_assembly.fa
transcriptome_fasta: /path/to/cdna.all.fa
readLength: 150
colData: /colData.xlsx
samples:
  WT1: WT1
  WT2: WT2
  WT3: WT3
  KO1: KO1
  KO2: KO2
  KO3: KO3

# Pre-processing and QC
sample_path: /data/fastq
outdir_fastp: /data/trimmed
outdir_fastqc: /data/QC

# STAR alignment parameters
build_star_index: true
star_index_dir: /STAR_index
outdir_star: /STAR_align
sjdbOverhang: 149
twopass: true

# rMATS-turbo parameters
rmats_path: /path/to/rmats-turbo/rmats.py
outdir_rmats: /rMATS-turbo
rmats_type: paired # otions: paired, single
libType: fr-firststrand # options fr-firststrand, fr-secondstrand, fr-unstranded
contrasts:
  KO-vs-WT:
  - KO
  - WT
rmats_filter:
  FDR: 0.01
  deltaPSI: 0.15

# featureCounts parameters
outdir_featureCounts: /featureCounts
feature_type: true # for paired-end data
DGE_filter:
  padj: 0.01
  FC: 1.5

# Salmon parameters
build_salmon_index: true
salmon_index_dir: /Salmon_index
outdir_salmon: /Salmon

# PSI parameters
outdir_psi: /PSI
gff: /path/to/reduced/annotation.gff
psi:
  paired: yes # "yes" for paired-end reads, "no" for single-end
  strand_specificity: reverse # options: reverse, yes, no
plot_groups:
  groups: [WT, KO]
  reference: WT
psi_gtf: /path/to/gene_annotation_canonical.gtf # if a different GTF file is wanted (e.g. only canonical transcripts)

# optional PSI plotting (default is to not generate plots)
generate_psi_plots: True # change to True if wanted
target_genes: /target_genes.txt

# SPLASH2
splash: /path/to/./splash
