# General parameters
gtf: path/to/GTF/file.gtf
genome_fasta: path/to/genome.dna.primary_assembly.fa
transcriptome_fasta: path/to/transcriptome.cdna.all.fa
readLength: 150
colData: colData.xlsx
samples:
  WT1: WT1
  WT2: WT2
  WT3: WT3
  KO1: KO1
  KO2: KO2
  KO3: KO3

# Pre-processing and QC
sample_path: data/fastq
outdir_fastp: data/trimmed
outdir_fastqc: outputs/QC

# STAR alignment parameters
build_star_index: true # set to false if pre-existing
star_index_dir: outputs/STAR_index
outdir_star: outputs/STAR_align
sjdbOverhang: 149 # specify for building the index, generally readlength -1
twopass: true

# rMATS-turbo parameters
rmats_path: path/to/rmats-turbo/rmats.py
outdir_rmats: outputs/rMATS-turbo
rmats_type: paired # options: paired, single
libType: fr-firststrand # options fr-firststrand, fr-secondstrand, fr-unstranded
contrasts:
  KO-vs-WT:
  - KO
  - WT

# featureCounts parameters
outdir_featureCounts: outputs/featureCounts
feature_type: true # for paired-end data

# Salmon parameters
build_salmon_index: true
salmon_index_dir: outputs/Salmon_index
outdir_salmon: outputs/Salmon

# PSI parameters
outdir_psi: outputs/PSI
gff: path/to/gene_annotation_reduced.gff
psi:
  paired: yes # "yes" for paired-end reads, "no" for single-end
  strand_specificity: reverse # options: reverse, yes, no

# optional PSI plotting
generate_psi_plots: true # change to false if not wanted
target_genes: path/to/target_genes.txt
plot_groups:
  groups: [WT, KO]
  reference: WT
psi_gtf: path/to/gene_annotation.gtf # if a different GTF file is wanted (e.g. only canonical transcripts)

# SPLASH2
splash: path/to/splash
