name: rnaseq_pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Python & Snakemake for pipeline orchestration
  - python=3.10.7
  - snakemake=7.7.0

  # R and related packages
  - r-base=4.4.2
  - r-yaml=2.3.10
  - r-stringr=1.5.1
  - r-scales=1.3.0
  - r-dplyr=1.1.4
  - r-readr=2.1.5
  - r-tidyr=1.3.1
  - bioconductor-dexseq=1.52.0
  - r-tidyverse=2.0.0
  - r-readxl=1.4.3
  - bioconductor-apeglm
  - r-purrr
  - bioconductor-rtracklayer=1.66.0

  # Bioinformatics tools and packages
  - singularity=2.6.0
  - fastqc=0.11.9
  - star=2.7.8a
  - samtools=1.19
  - fastp=0.23.2
  - multiqc=1.14
  - subread=2.0.3
  - salmon=1.10.1
  - bedtools=2.30.0
  - htseq=2.0.2
  - pysam=0.20.0
  - deeptools=3.5.5
  - wiggletools=1.2.11

  # Alternative splicing analysis
  - rmats=4.3.0

  # Optional: glibc-locales is typically a system package and may not be needed in Conda
  # - glibc-locales
